config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  scope 'wxoss' do
    mount WeixinRailsMiddleware::Engine, at: "/"

    constraint = lambda { |request| !request.session[:admin].blank? }
    constraints constraint do
      mount Sidekiq::Web, at: '/sidekiq', as: :sidekiq
    end

    get "wx_official_accounts/getAccountList", to: 'wx_official_accounts#getAccountList'
    get "wx_official_accounts/setOfficialAccount2Session", to: 'wx_official_accounts#setOfficialAccount2Session'
    resources :wx_official_accounts do
      get 'get_resources', on: :member
      get 'get_users', on: :member
      resources :wx_auto_response

    end

    get 'welcome/index'
    post 'welcome/login'
    get 'welcome/getmenu'
    get 'welcome/logout'
    get 'wx_articles/resources'  => 'wx_resources#index'
    post 'wx_articles/resources'  => 'wx_resources#create'
    get 'wx_articles/resources/getimgdata' => 'wx_resources#getimgdata'
    post 'wx_articles/resources/create_group' => 'wx_resources#create_group'
    post 'wx_articles/resources/modify_img_group' => 'wx_resources#modify_img_group'
    post 'wx_articles/resources/modify_group' => 'wx_resources#modify_group'
    post 'wx_articles/resources/del_group' => 'wx_resources#del_group'
    post 'wx_articles/resources/rename' => 'wx_resources#rename'
    post 'wx_articles/resources/delete_image' => 'wx_resources#destroy'
    get 'wx_articles/edit' => 'wx_articles#edit'
    post 'wx_articles/delete' => 'wx_articles#destroy'
    resources :wx_articles

    post 'wx_users/get_fans_info'
    post 'wx_users/add_mark'
    post 'wx_users/create_group'
    post 'wx_users/rename_group'
    post 'wx_users/del_group'
    get 'wx_users/get_user_list'
    post 'wx_users/search'
    post 'wx_users/batch_set_tag'
    post 'wx_users/del_tag'
    post 'wx_users/set_black'
    post 'wx_users/cancle_black'
    post 'wx_users/fixgroupcnt'
    resources :wx_users
    get 'wx_msganalysis' => 'wx_msganalysis#index'
    get 'wx_msganalysis/keyword' => 'wx_msganalysis#keyword'
    get 'wx_msganalysis/fdevreport' => 'wx_msganalysis#fdevreport'
    get 'wx_interfaceanalysis' => 'wx_interfaceanalysis#index'
    get 'wx_useranalysis' => 'wx_useranalysis#index'

    get 'wxserver/netauth' => 'wxserver#netauth'

    resources :wx_batch_messages do
      get 'get_provinces_by_country_id', on: :collection
      get 'get_cities_by_province_id', on: :collection
      post 'batchSendMessage', on: :collection
      get 'batch_messages_history', on: :collection
      get 'delete_message', on: :collection
    end

    resources :wx_auto_responses do
      post 'update_response', on: :collection
      post 'create_response', on: :collection
      get 'delete_response', on: :collection
      post "create_key_response", on: :collection
      get "delete_wx_key_response", on: :collection
      post 'update_key_response', on: :collection
    end

    resources :wx_menus do
      post 'create_menu', on: :collection
    end

    resources :wx_shake_activities do
      get 'redirect', on: :collection
      get 'screenshow', on: :collection
      get 'runway', on: :collection
      get 'get_userdata', on: :collection
      get 'awardlist', on: :collection
      get 'update_status', on: :collection
      get 'get_status', on: :collection
      post 'save_count', on: :collection
      get 'get_awardstatus', on: :collection
    end

    resources :wx_shake_managements do
      get 'prizelist', on: :collection
      post 'uploadpic', on: :collection
      post 'deletepic', on: :collection
    end

    resources :wx_wheel_activities do
      get 'redirect', on: :collection
      get 'wheel', on: :collection
      post 'update_info', on: :collection
      get 'query_record', on: :collection
    end

    resources :wx_wheel_managements do
      get 'prizelist', on: :collection
    end

  end

  root 'welcome#index'

end

app/models/wx_official_account.rb
class WxOfficialAccount < ActiveRecord::Base

  # validates_presence_of :wechat_name, :message => "wechat_name can not null"
  # validates_presence_of :original_id, :message => "original_id can not null"
  validates_presence_of :wechat_type, :message => "公众号类型不能为空"
  validates :original_id, uniqueness: {message: "%{value}已经存在"} #　原始Ｉｄ的唯一性check
  validates :wechat_account, uniqueness: {message: "%{value}已经存在"} #微信号的唯一性check
  validates :app_id, uniqueness: {message: "%{value}已经存在"} #微信号的唯一性check
  after_create :mk_resource_dir
  has_many :wx_auto_responses, :dependent => :destroy
  has_many :wx_key_responses, :dependent => :destroy
  has_many :wx_batch_send_messages, :dependent => :destroy
  # It will auto generate weixin token and secret
  include WeixinRailsMiddleware::AutoGenerateWeixinTokenSecretKey
  before_create do
    self.encoding_aes_key = generate_encoding_aes_key
  end
  validate :app_right_check, on: :create
  attr_reader :client

  has_many :wx_resources, :dependent => :destroy
  has_many :wx_user_groups, :dependent => :destroy
  has_many :wx_users, :dependent => :destroy
  has_many :wx_articles, :dependent => :destroy
  has_many :wx_resource_groups, :dependent => :destroy
  # 自定义菜单
  has_many :wx_menus, dependent: :destroy
  # 当前公众账号的所有父级菜单
  has_many :parent_menus, -> { includes(:sub_menus).where(parent_id: nil, is_show: true).order("sort").limit(3) },
           class_name: "WxMenu", foreign_key: :wx_official_account_id

  def wx_post(url, params)
    wx_log_info("当前公众号：#{self.wechat_name}")
    wx_log_info("接口请求地址：#{url}")
    wx_log_info("接口请求参数：#{params}")
    result = client.http_post(url, params, {}, WeixinAuthorize::CUSTOM_ENDPOINT)
    unless result.is_ok?
      wx_log_info("接口返回错误信息：#{result.full_error_message}")
    end
    return result
  end

  def wx_get(url, params={})
    wx_log_info("公众号名称：#{self.wechat_name}")
    wx_log_info("接口请求地址：#{url}")
    wx_log_info("接口请求参数：#{params}")
    result = client.http_get(url, params, WeixinAuthorize::CUSTOM_ENDPOINT)
    unless result.is_ok?
      wx_log_info("错误信息：#{result.full_error_message}")
    end
    return result
  end

  def wx_log_info(message)
    Utils::WxInvokeLogger.info message
  end

  def mk_resource_dir
    Dir.mkdir("public/uploads/#{self.id}")
  end

  def get_news_params_by_mediaid media_id
    _article = self.wx_articles.find(media_id)
    _img_url = self.wx_resources.find(_article.cover_file_id).wx_url
    return Hash["link_url" => _article.content_url, "pic_url" => _img_url, "title" => _article.title, "desc" => _article.digest]
  end

  # 公众号创建菜单方法的定义
  def build_menu
    Jbuilder.encode do |json|
      json.button (parent_menus) do |menu|
        json.name menu.name
        if menu.has_sub_menu?
          json.sub_button(menu.sub_menus) do |sub_menu|
            json.type sub_menu.type
            json.name sub_menu.name
            sub_menu.button_type(json)
          end
        else
          json.type menu.type
          menu.button_type(json)
        end
      end
    end
  end

  def client
    @client = WeixinAuthorize::Client.new(self.app_id, self.app_secret)
  end

  private
  def app_right_check
    @client = WeixinAuthorize::Client.new(self.app_id, self.app_secret)
    # 是合法的appId和appSecret
    if @client.is_valid?
      begin
        if self.expired_at.nil?|| self.expired_at.to_i < Time.now.to_i
          self.access_token = @client.custom_access_token = @client.get_access_token
          self.expired_at = Time.at(@client.expired_at)
        end
      rescue Exception => e
        if e.message.include? "APPID"
          errors.add(:msg_content, "不合法的app_id")
        elsif e.message.include? "appsecret"
          errors.add(:msg_content, "不合法的app_secret")
        end
      end
      # 不合法的appId和appSecret
    else
      errors.add(:msg_content, "appId和appSecret无效")
    end
  end

  def generate_encoding_aes_key
    WeiXinUniqueToken.generate(generator: :hex, size: 22)[1..43]
  end
end

app/controllers/wx_official_accounts_controller.rb
class WxOfficialAccountsController < ApplicationController
  layout 'application'
  before_action :set_wx_official_account, only: [:show, :edit, :update, :destroy, :get_resources, :get_users]

  def getAccountList
    render json: {"list" => WxOfficialAccount.all, "sessionAccountid" => session[:current_official_account_id]}
  end

  def setOfficialAccount2Session
    session[:current_official_account_id] = params[:current_official_account_id]
    @current_wx_official_account = WxOfficialAccount.find(params[:current_official_account_id])
    session[:current_official_account_wechat_name] = @current_wx_official_account.wechat_name

    render json: {"result" => "ok", status => "200 ok"}
  end

  # GET /wx_official_accounts
  # GET /wx_official_accounts.json
  def index
    @name = params[:search_name]
    if @name == nil || @name == ''
      @current_wx_official_account = WxOfficialAccount.all
      @search_name = '请输入公众号名称'
    else
      @current_wx_official_account = WxOfficialAccount.where("wechat_name LIKE '%#{@name}%'")
      @search_name = @name
    end
  end

  # GET /wx_official_accounts/1
  # GET /wx_official_accounts/1.json
  def show
    @wx_official_account.client

  end

  # GET /wx_official_accounts/new
  def new
    @wx_official_account = WxOfficialAccount.new

  end

  # GET /wx_official_accounts/1/edit
  def edit
  end

  # POST /wx_official_accounts
  # POST /wx_official_accounts.json
  def create
    @wx_official_account = WxOfficialAccount.new(wx_official_account_params)

    respond_to do |format|
      if @wx_official_account.save
        format.html { redirect_to @wx_official_account, notice: 'Wx official account was successfully created.' }
        format.json { render :show, status: :created, location: @wx_official_account }
      else
        format.html { render :new }
        # format.json { render json: @wx_official_account.errors.messages, status: :unprocessable_entity }
        # render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @wx_official_account.update(update_wx_official_account_params)
        format.html { redirect_to @wx_official_account, notice: 'Wx official account was successfully updated.' }
        format.json { render :show, status: :ok, location: @wx_official_account }
      else
        format.html { render :edit }
        format.json { render json: @wx_official_account.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_resources
    count_return = @wx_official_account.wx_get(GET_MATERIALCOUNT)
    WxResource.wx_data_pull(@wx_official_account, count_return.result[:image_count])
    WxArticle.wx_data_pull(@wx_official_account, count_return.result[:news_count])
    @wx_official_account.update(:resource_flag => 1)
    render :json => {:err_msg => '获取成功'}
  end

  def get_users
    WxUser.wx_data_pull(@wx_official_account)
    WxUserGroup.wx_data_pull(@wx_official_account)
    render :json => {:err_msg => '获取成功'}
  end

  # DELETE /wx_official_accounts/1
  # DELETE /wx_official_accounts/1.json
  def destroy
    account_id = @wx_official_account.id
    if @wx_official_account.destroy
      session[account_id] = nil
    end
    respond_to do |format|
      format.html { render :text => '' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_wx_official_account
    @wx_official_account = WxOfficialAccount.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wx_official_account_params
    params.require(:wx_official_account).permit(:wechat_name, :original_id, :wechat_type, :wechat_account, :app_id, :app_secret,:wx_m_enterpriseclient_id)
  end

  def update_wx_official_account_params
    params.require(:wx_official_account).permit(:wechat_name, :original_id, :wechat_type, :wechat_account)
  end
end

app/helpers/wx_official_accounts_helper.rb
module WxOfficialAccountsHelper
end

app/views/wx_official_accounts/_form.html.erb
<%= form_for(@wx_official_account) do |f| %>
    <div class="add-data-form">
      <div class="add-item">
        <label class="add-label"><span class="required">*</span><%= f.label :wechat_name, "公众号名称：" %></label>
        <%= f.text_field :wechat_name, :class => "add-ipt"%>
      </div>
      <div class="add-item">
        <label class="add-label"><span class="required">*</span><%= f.label :original_id, "公众号原始ID：" %></label>
        <%= f.text_field :original_id, :class => "add-ipt" %>
      </div>
      <div class="add-item">
        <%= f.label :wechat_account, "微信号：", :class => "add-label" %>
        <%= f.text_field :wechat_account, :class => "add-ipt" %>
      </div>
      <div class="add-item">
        <label class="add-label"><span class="required">*</span><%= f.label :app_id, "AppID(公众号）：" %></label>
        <%= f.text_field :app_id, :class => "add-ipt"%>
        <span class="prompt">用于自定义菜单等高级功能</span>
      </div>
      <div class="add-item app_secret_div">
        <label class="add-label"><span class="required">*</span><%= f.label :app_secret, "AppSecret："%></label>
        <%= f.text_field :app_secret, :class => "add-ipt"%>
        <span class="prompt">用于自定义菜单等高级功能</span>
      </div>

      <div class="add-item">
        <% enterprise_array = WxMEnterpriseclient.all.map { |enterprise| [enterprise.ecname, enterprise.id] } %>
        <label class="add-label"><span class="required">*</span><%= f.label :wx_m_enterpriseclient_id, "公众号所属集团：" %></label>
        <%= f.select :wx_m_enterpriseclient_id, enterprise_array, {:prompt => "请选择"}, {:class => 'add-ipt'} %>
      </div>

      <div class="add-item">
        <label class="add-label"><span class="required">*</span><%= f.label :wechat_type, "公众号类型：" %></label>
        <%= f.select :wechat_type, [["未认证订阅号", 1], ["已认证订阅号", 2], ["未认证服务号", 3], ["已认证服务号", 4]], {:prompt => "请选择"}, {:class => 'add-ipt'} %>
        <span class="prompt">认证服务号或订阅号是指每年向微信官方交300元认证费的公众号</span>
      </div>

      <!--<div class="add-item">-->
        <!--<%= f.label :accesstype, "微信多客服：", :class => "add-label" %>-->
        <!--<label class="radio-label"><input type="checkbox" name="" id="" checked>启用微客服</label><a href="javascript:void(0)">查看如何设置？</a>-->
      <!--</div>-->
    </div>
    <div class="tool_bar">
      <%= f.submit "确认", :class => "btn" ,id:"mysubmit"%>
      <%= link_to '取消', wx_official_accounts_path, class: "btn cancel",style:"min-width:32px;display:inline-block;height:32px;width:35px;"%>
    </div>
<% end %>

<script type="text/javascript">

  $(function(){
    <% if @wx_official_account.errors.any? %>
      <% @wx_official_account.errors.messages[:msg_content].each do |message| %>
        $('<div class="results"  style="position:fixed;z-index:999;top:0px "><%= message %></div>').appendTo("body").fadeOut(6000);
      <% end %>
    <% end %>

    $(".manager").addClass("selected");
    //非空字段的check
    $("#mysubmit").on("click",function(){
      var weOrginalInput = $("#wx_official_account_original_id");
      var wechat_name_Input = $("#wx_official_account_wechat_name");

      var wechatTypeInput = $("#wx_official_account_wechat_type");
      var enterpriseclient_id = $("#wx_official_account_wx_m_enterpriseclient_id");
      var app_id_Input = $("#wx_official_account_app_id");
      var app_secret_Input = $("#wx_official_account_app_secret");

      //　微信号名称不能为空
      if($.trim(wechat_name_Input.val()) == ''){
        wechat_name_Input.focus();
        return false;
      }
      // 微信号原始ＩＤ不能为空
      else if($.trim(weOrginalInput.val()) == ''){
        weOrginalInput.focus();
        return false;
      }
      //appid不能为空
      else if($.trim(app_id_Input.val()) == ''){
        app_id_Input.focus();
        return false;
      }
      //app_secret不能为空
      else if($.trim(app_secret_Input.val()) == ''){
        app_secret_Input.focus();
        return false;
      }
      //enterpriseclient_id不能为空
      else if($.trim(enterpriseclient_id.val()) == ''){
        enterpriseclient_id.focus();
        $('<div class="results"  style="position:fixed;z-index:999;top:0px ">请选择公众号所属集团</div>').appendTo("body").fadeOut(6000);
        console.log(111);
        return false;
      }
      //wechat_type不能为空
      else if($.trim(wechatTypeInput.val()) == ''){
        $('<div class="results"  style="position:fixed;z-index:999;top:0px ">请选择公众号类型</div>').appendTo("body").fadeOut(6000);
        return false;
      }
      else{
        return true;
      }

    });

  });



</script>

app/views/wx_official_accounts/edit.html.erb
<div class="col_main">
  <div class="main">
    <div class="main_hd">
      <h2>公众号管理</h2>
    </div>
    <div class="main_bd" style="border-top: 1px solid #e7e7eb;">
      <%= render 'form' %>
      </div>
  </div>
</div>
<script type="text/javascript">
  //appid和appsecret不可以被修改
  $("#wx_official_account_app_id,#wx_official_account_app_secret").attr("disabled","true");
</script>

app/views/wx_official_accounts/index.html.erb
<%= content_for :content do %>
    <div class="main_hd">
        <h2 id="model_title"> 公众号管理</h2>
        
      </div>
        <div class="searchBox">

          <div class="search">
        <input id="search_name" type="text" style="color:#8d8d8d" onFocus="if(this.value=='请输入公众号名称'){this.value='';this.style.color='#8d8d8d'};" onblur="if(this.value==''){this.value='请输入公众号名称';this.style.color='#8d8d8d'}" value= <%= @search_name %>>
      </div>

      <%= button_to('搜索', wx_official_accounts_path, method: :get, class: "btn search_btn",
                    params: {search_name: ''}, id: "searchBtn") %>

      <%= button_to '添加公众号', new_wx_official_account_path, class: "btn add_btn", method: :get %>
      <table class="J_table_hover data-table">
        <thead>
        <tr>
          <th>名称</th>
          <th>微信号</th>
          <th colspan="5" style="text-align: center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @current_wx_official_account.each do |wx_official_account| %>
            <tr>
              <td class="name"><%= wx_official_account.wechat_name %></td>
              <td><%= wx_official_account.wechat_account %></td>
              <td><%= link_to '详情', wx_official_account %></td>
              <td><%= link_to '修改', edit_wx_official_account_path(wx_official_account) %></td>
              <td>
                <%= link_to '删除', wx_official_account, method: :delete, :class => 'msg_card_opr_item_inner remove'%>
              </td>
              <td><%= link_to '获取素材', get_resources_wx_official_account_path(wx_official_account), remote: true, :class => 'get_resources' %></td>
              <td><%= link_to '获取用户', get_users_wx_official_account_path(wx_official_account), remote: true, :class => 'get_users' %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <!--   </div>
    </div> -->

    <script type="text/javascript">
      $(function () {
        $(".manager").addClass("selected");
        $("#searchBtn").on("click", function () {
          var searchName = $("#search_name").val();
          if (searchName == '请输入公众号名称' || $.trim(searchName) == '') {
            $(this).parents().submit();
          }
          else {
            $("input[name='search_name']").val(searchName);
            $(this).parents().submit();
          }
        })
        $(".get_resources,.get_users").on('click', function () {
          var resource_Link = $(this);
          $.ajax({
            url: resource_Link.attr("href"),
            success: function (data) {
              $('<div class="results"  style="position:fixed;z-index:999;top:0px ">' + data.err_msg + '</div>').appendTo("body").fadeOut(2000);
            },
            error: function (msg) {
              $('<div class="results"  style="position:fixed;z-index:999;top:0px ">获取失败</div>').appendTo("body").fadeOut(2000);
            }
          });
          return false;
        });
        $('a.remove').click(function () {
          var wechat_name = $(this).parent().parent().find(".name").html();
          $(".mod-popover").remove();
          $(this).after('<div class="mod-popover" style="left:-90px"><div class="mod-popover_arrow"></div>' +
              '<div class="mod-popover_inner" style="width: 234px;"><div class="popover_content">确定要删除 '+wechat_name+' 公众号吗？</div>' +
              '<div class="popover_bar"><button class="btn btn_primary remove">确认</button><button ' +
              'class=" btn btn_primary cancel">取消</button></div></div></div>');
          var deleteLink = $(this);
          $("button.remove").on('click', function () {
            $.ajax({
              type: "DELETE",
              url: deleteLink.attr("href"),
              success: function (data) {
                $('<div class="results"  style="position:fixed;z-index:999;top:0px ">删除成功</div>').appendTo("body");
                location.reload();
              },
              error: function (msg) {
                $('<div class="results"  style="position:fixed;z-index:999;top:0px ">删除失败</div>').appendTo("body");
                location.reload();
              }
            });
          });
          $("button.cancel").on('click', function () {
            $(".mod-popover").remove();
          });
          return false;
        });


      });
    </script>



<% end %>

app/views/wx_official_accounts/new.html.erb
<div class="col_main">
<div class="main">
  <div class="main_hd">
    <h2>公众号管理</h2>
  </div>
  <div class="main_bd">
    <div class="highlight_box">
      <div class="icon_wrap icon_add"></div>
      <div class="txt"><h2>添加公众号</h2>
        <p>通过填写公众号信息轻松实现管理系统对粉丝信息的获取和自定义菜单的配置。系统自动生成微信公众账号接口配置参数（接口URL和接口Token）</p>
      </div>
    </div>
    <div>
      <%= render 'form' %>
    </div>
  </div>
</div>
</div>

app/views/wx_official_accounts/show.html.erb
<div class="col_main">
  <div class="main">
    <div class="main_hd">
      <h2>公众号管理</h2>
    </div>
    <div class="main_bd" style="border-top: 1px solid #e7e7eb;">
      <div>
        <div class="add-data-form">
          <div class="add-item">
            <label class="add-label">公众号名称：</label>
            <%= @wx_official_account.wechat_name %>
          </div>
          <div class="add-item">
            <label class="add-label">公众号原始ID：</label>
            <%= @wx_official_account.original_id %>
          </div>
          <div class="add-item">
            <label class="add-label">微信号：</label>
            <%= @wx_official_account.wechat_account %>
          </div>
          <div class="add-item">
            <label class="add-label">AppID(公众号）：</label>
            <%= @wx_official_account.app_id %>
          </div>
          <div class="add-item">
            <label class="add-label">AppSecret(公众号）：</label>
            <%= @wx_official_account.app_secret %>
          </div>
          <div class="add-item">
            <label class="add-label">公众号所属集团：</label>
            <%= WxMEnterpriseclient.find(@wx_official_account.wx_m_enterpriseclient_id).ecname %>
          </div>
          <div class="add-item">
            <label class="add-label">公众号类型：</label>
            <%	if @wx_official_account.wechat_type == 1%>
                未认证订阅号
            <%	elsif @wx_official_account.wechat_type == 2%>
                已认证订阅号
            <%	elsif @wx_official_account.wechat_type == 3%>
                未认证服务号
            <%	elsif @wx_official_account.wechat_type == 4%>
                已认证服务号
            <% end %>
          </div>
          <div class="add-item">
            <label class="add-label">服务器地址：</label>
            <%= weixin_engine.weixin_server_url(@wx_official_account.weixin_secret_key).sub!(request.base_url, WEIXIN_SERVER) %>
          </div>
          <div class="add-item">
            <label class="add-label">令牌：</label>
            <%= @wx_official_account.weixin_token %>
          </div>
          <div class="add-item">
            <label class="add-label">消息秘钥：</label>
            <%= @wx_official_account.encoding_aes_key %>
          </div>
        </div>
        <div class="tool_bar">
          <%= button_to "修改", edit_wx_official_account_path(@wx_official_account), :class => "btn btn_primary", method: :get %>
          <%= button_to "返回", wx_official_accounts_path, :class => " btn btn_primary cancel", method: :get %>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $(".manager").addClass("selected");
</script>
<style>
  .button_to{
    display: inline-block;}
</style>