config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  scope 'wxoss' do
    mount WeixinRailsMiddleware::Engine, at: "/"

    constraint = lambda { |request| !request.session[:admin].blank? }
    constraints constraint do
      mount Sidekiq::Web, at: '/sidekiq', as: :sidekiq
    end

    get "wx_official_accounts/getAccountList", to: 'wx_official_accounts#getAccountList'
    get "wx_official_accounts/setOfficialAccount2Session", to: 'wx_official_accounts#setOfficialAccount2Session'
    resources :wx_official_accounts do
      get 'get_resources', on: :member
      get 'get_users', on: :member
      resources :wx_auto_response

    end

    get 'welcome/index'
    post 'welcome/login'
    get 'welcome/getmenu'
    get 'welcome/logout'
    get 'wx_articles/resources'  => 'wx_resources#index'
    post 'wx_articles/resources'  => 'wx_resources#create'
    get 'wx_articles/resources/getimgdata' => 'wx_resources#getimgdata'
    post 'wx_articles/resources/create_group' => 'wx_resources#create_group'
    post 'wx_articles/resources/modify_img_group' => 'wx_resources#modify_img_group'
    post 'wx_articles/resources/modify_group' => 'wx_resources#modify_group'
    post 'wx_articles/resources/del_group' => 'wx_resources#del_group'
    post 'wx_articles/resources/rename' => 'wx_resources#rename'
    post 'wx_articles/resources/delete_image' => 'wx_resources#destroy'
    get 'wx_articles/edit' => 'wx_articles#edit'
    post 'wx_articles/delete' => 'wx_articles#destroy'
    resources :wx_articles

    post 'wx_users/get_fans_info'
    post 'wx_users/add_mark'
    post 'wx_users/create_group'
    post 'wx_users/rename_group'
    post 'wx_users/del_group'
    get 'wx_users/get_user_list'
    post 'wx_users/search'
    post 'wx_users/batch_set_tag'
    post 'wx_users/del_tag'
    post 'wx_users/set_black'
    post 'wx_users/cancle_black'
    post 'wx_users/fixgroupcnt'
    resources :wx_users
    get 'wx_msganalysis' => 'wx_msganalysis#index'
    get 'wx_msganalysis/keyword' => 'wx_msganalysis#keyword'
    get 'wx_msganalysis/fdevreport' => 'wx_msganalysis#fdevreport'
    get 'wx_interfaceanalysis' => 'wx_interfaceanalysis#index'
    get 'wx_useranalysis' => 'wx_useranalysis#index'

    get 'wxserver/netauth' => 'wxserver#netauth'

    resources :wx_batch_messages do
      get 'get_provinces_by_country_id', on: :collection
      get 'get_cities_by_province_id', on: :collection
      post 'batchSendMessage', on: :collection
      get 'batch_messages_history', on: :collection
      get 'delete_message', on: :collection
    end

    resources :wx_auto_responses do
      post 'update_response', on: :collection
      post 'create_response', on: :collection
      get 'delete_response', on: :collection
      post "create_key_response", on: :collection
      get "delete_wx_key_response", on: :collection
      post 'update_key_response', on: :collection
    end

    resources :wx_menus do
      post 'create_menu', on: :collection
    end

    resources :wx_shake_activities do
      get 'redirect', on: :collection
      get 'screenshow', on: :collection
      get 'runway', on: :collection
      get 'get_userdata', on: :collection
      get 'awardlist', on: :collection
      get 'update_status', on: :collection
      get 'get_status', on: :collection
      post 'save_count', on: :collection
      get 'get_awardstatus', on: :collection
    end

    resources :wx_shake_managements do
      get 'prizelist', on: :collection
      post 'uploadpic', on: :collection
      post 'deletepic', on: :collection
    end

    resources :wx_wheel_activities do
      get 'redirect', on: :collection
      get 'wheel', on: :collection
      post 'update_info', on: :collection
      get 'query_record', on: :collection
    end

    resources :wx_wheel_managements do
      get 'prizelist', on: :collection
    end

  end

  root 'welcome#index'

end

app/controllers/wx_auto_responses_controller.rb
class WxAutoResponsesController < WeixinClientController
  # before_action :set_wx_auto_response, only: [:update_response, :delete_response]
  layout 'wx_auto_responses'


  def index
    #  type为nil，是被添加自动回复页面
    if params[:type].nil?
      setResponseData(1)
      render "index"
    elsif params[:type]=="message_response" #消息自动回复
      setResponseData(2)
      render params[:type]
    else
      @wx_key_responses = @current_wx_official_account
                              .wx_key_responses
      # @wx_articles = @current_wx_official_account.wx_articles
      @wx_articles = @current_wx_official_account.wx_articles.group("news_id").having("media_id is not null and cover_file_id is not null")

      setImgGroupsDatas
      render params[:type]
    end
  end


  def update_response
    get_wx_auto_response params[:wx_auto_response][:event_type]
    if @wx_auto_response.update({"res_type" => params[:wx_auto_response][:res_type], "res_content" => params[:wx_auto_response][:res_content], "event_type" => params[:wx_auto_response][:event_type]})
      render json: {"result" => "success"}
    else
      render json: {"result" => "false"}
    end
  end


  # 修改已有的关键字回复规则
  def update_key_response
    wx_key_response = WxKeyResponse.find(params[:id])
    wx_key_response.rule_name = params[:rule_name]
    wx_key_response.is_response_all= [:is_response_all]
    if wx_key_response.save
      # 循环保存关键字信息
      keys = params[:keys]
      keys.map do |keyObj|
        # id为空，是新增的关键字
        if keyObj[1][:id].nil?
          @wx_key = wx_key_response.wx_keys.new
          @wx_key.wx_key_response_id = wx_key_response.id
          @wx_key.key = keyObj[1][:key]
          @wx_key.is_match = keyObj[1][:is_match]
          @wx_key.save
          # id不为空是删除或者修改关键字
        else
          @wx_key = WxKey.find(keyObj[1][:id])
          # 是删除
          if keyObj[1][:is_delete]
            @wx_key.destroy
          else
            @wx_key.key = keyObj[1][:key]
            @wx_key.is_match = keyObj[1][:is_match]
            @wx_key.save
          end
        end
      end


      # 循环保存关键字回复的内容信息
      reply_content = params[:reply_content]
      reply_content.map do |replyObj|

        # 如果ｉｄ是空，就是新增的回复内容
        if replyObj[1][:id].nil?
          @wx_respnse_content = wx_key_response.wx_response_contents.new
          @wx_respnse_content.wx_key_response_id = wx_key_response.id
          # 如果回复内容是文字
          if replyObj[1][:content_type] == '0'
            @wx_respnse_content.text_content = replyObj[1][:text_content]
          else
            @wx_respnse_content.media_content = replyObj[1][:media_content]
          end
          @wx_respnse_content.content_type = replyObj[1][:content_type]
          @wx_respnse_content.save
        #   Id 不为空是删除或者修改操作
        else
          @wx_respnse_content = WxResponseContent.find(replyObj[1][:id])
          # 是删除
          if replyObj[1][:is_delete]
            @wx_respnse_content.destroy
          else
            # 如果回复内容是文字
            if replyObj[1][:content_type] == '0'
              @wx_respnse_content.text_content = replyObj[1][:text_content]
            else
              @wx_respnse_content.media_content = replyObj[1][:media_content]
            end
            @wx_respnse_content.content_type = replyObj[1][:content_type]
            @wx_respnse_content.save
          end
        end
      end
      render json: {"result" => "success"}
    else
      render json: {"result" => "false"}
    end
  end


  # 删除回复
  def delete_response
    get_wx_auto_response params[:event_type]
    if @wx_auto_response.nil?
      render json: {"result" => "false"}
    else
      @wx_auto_response.destroy
      render json: {"result" => "success"}
    end
  end

  # 删除
  def delete_wx_key_response
    get_wx_key_response params[:rule_id]
    if @wx_key_response.nil?
      render json: {"result" => "false"}
    else
      @wx_key_response.destroy
      render json: {"result" => "success"}
    end
  end

  # 新建新的自动回复
  def create_response
    @wx_auto_response = @current_wx_official_account.wx_auto_responses.new
    @wx_auto_response.res_type = params[:wx_auto_response][:res_type]
    @wx_auto_response.event_type = params[:wx_auto_response][:event_type]
    @wx_auto_response.res_content = params[:wx_auto_response][:res_content]

    @wx_auto_response.wx_official_account_id = session[:current_official_account_id]

    @wx_auto_response.original_id=@current_wx_official_account.original_id

    if @wx_auto_response.save
      render json: {"result" => "success"}
    else
      render json: {"result" => "false"}
    end
  end


  # 新建关键字自动回复数据
  def create_key_response
    wx_key_response = @current_wx_official_account.wx_key_responses.new
    wx_key_response.rule_name= params[:rule_name]
    wx_key_response.is_response_all= [:is_response_all]
    # 如果关键字回复保存成功，则保存相应的关键字和回复的内容
    if (wx_key_response.save)
      # 循环保存关键字信息
      keys = params[:keys]
      keys.map do |keyObj|
        wx_key = wx_key_response.wx_keys.new
        wx_key.key = keyObj[1][:key]
        wx_key.wx_key_response_id = wx_key_response.id
        wx_key.is_match = keyObj[1][:is_match]
        wx_key.save
      end

      # 循环保存关键字回复的内容信息
      reply_content = params[:reply_content]
      reply_content.map do |replyObj|
        wx_respnse_content = wx_key_response.wx_response_contents.new
        # 如果回复内容是文字
        if replyObj[1][:content_type] == '0'
          wx_respnse_content.wx_key_response_id = wx_key_response.id
          wx_respnse_content.content_type = replyObj[1][:content_type]
          wx_respnse_content.text_content = replyObj[1][:text_content]
        else
          wx_respnse_content.wx_key_response_id = wx_key_response.id
          wx_respnse_content.content_type = replyObj[1][:content_type]
          wx_respnse_content.media_content = replyObj[1][:media_content]
        end
        wx_respnse_content.save
      end

      render json: {"result" => "success"}
    else
      render json: {"result" => "false"}
    end
  end


  private
  def wx_auto_response_params
    params.require(:wx_auto_response).permit(:res_content, :res_img_cache, :res_type, :event_type, :remote_res_img_url)
  end

  def get_wx_auto_response event_type
    @wx_auto_response = @current_wx_official_account.wx_auto_responses.find_by("event_type=" + event_type)

  end

  def get_wx_key_response rule_id
    @wx_key_response = @current_wx_official_account.wx_key_responses.find_by("id=" + rule_id)

  end


  def setResponseData event_type
    unless @current_wx_official_account.nil?
      @wx_auto_response = @current_wx_official_account
                              .wx_auto_responses.find_by("event_type=#{event_type}")
      # 有此自动回复，并且不是文字的回复
      if @wx_auto_response != nil and @wx_auto_response.res_type != 1
        @wx_resource = @current_wx_official_account
                           .wx_resources.find(@wx_auto_response.res_content)
      end
      setImgGroupsDatas
      # @group_map["no_name"] = no_name_group

    end
  end

  def setImgGroupsDatas
    # 此公众号下面的所有图片资源
    @img_resouces = @current_wx_official_account
                       .wx_resources.where("resource_type=2 and deleted=0")
    # 此公众号下面的所有图片分组
    img_groups = @current_wx_official_account.wx_resource_groups

    @group_map = Hash.new
    @group_name_map = Hash.new
    no_name_group = Array.new


    @img_resouces.each do |img_resource|
      # 是为分组的img_resource
      if img_resource.wx_resource_group_id == 1
        no_name_group.append(img_resource)
      end
    end
    @group_map[1] = no_name_group
    @group_name_map[1] = "未分组"

    img_groups.each do |group|
      @group_name_map[group.id] = group.name
      group_array = Array.new
      @img_resouces.each do |img_resource|
        if img_resource.wx_resource_group_id == group.id
          group_array.append(img_resource)
        end
      end
      @group_map[group.id] = group_array
    end
  end

end

app/views/wx_auto_responses/edit.html.erb
<h2>edit page.....</h2>
<%= render 'form' %>

app/views/wx_auto_responses/index.html.erb
<%= content_for :css do %>
    <%= javascript_include_tag 'ipmana', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'jquery-ui.min', 'data-turbolinks-track' => true %>
<% end %>
<%= content_for :response do %>
    <div id="tabBoxA" class="tabBox">
      <ul class="tabList" id="tabListA">
        <li class="hot" id="res_text" data-value=1><i class="icon_txt"></i>文字</li>
        <li id="res_pic" data-value=2><i class="icon_txt icon_img"></i>图片</li>
        <li id="res_audio" data-value=3><i class="icon_txt icon_voice"></i>语音</li>
        <li id="res_vedio" data-value=4><i class="icon_txt icon_video"></i>视频</li>
      </ul>
      <div id="tabOutBoxA">
        <!--文字-->
        <div class="tabOutList">
          <div class="edit_area">
            <% if @wx_auto_response and @wx_auto_response.res_type == 1 %>
                <textarea><%= @wx_auto_response.res_content %></textarea>
            <% else %>
                <textarea maxlength="600"></textarea>
            <% end %>
          </div>
          <div class="editor_toolbar">
            <div class="editor_tip">最多可以输入600个字</div>
          </div>
        </div>
        <!--图片-->
        <div class="tabOutList" style="display: none;">
          <div class="inner">

            <div class="img_item_bd" id="img_item" hidden>
              <img class="pic" src="" style="height:70px;width:70px;">
              <a href="#" id="auto_img_del">删除</a>
            </div>


            <div class="create_access auto_img_choice">
              <a href="#" id="img_modal"><i class="icon36 icon36_add"></i>
                <strong>从素材库中选择</strong></a>
            </div>

            <div class="create_access auto_img_choice">
              <a id="filePicker1">
                <i class="icon36 icon36_add"></i>
                <strong>上传图片</strong>
                <ul class="upload_file_box">
                </ul>
              </a>
              </a>
            </div>

          </div>
        </div>
        <!--语音-->
        <div class="tabOutList" style="display: none;">
          <div class="inner">
            <div class="create_access">
              <a href="#" id="audio_modal"><i class="icon36 icon36_add"></i>
                <strong>从素材库中选择</strong></a>
            </div>
            <div class="create_access">
              <a href="#"><i class="icon36 icon36_add"></i>
                <strong>新建语音</strong></a>
            </div>
          </div>
        </div>
        <!--视频-->
        <div class="tabOutList" style="display: none;">
          <div class="inner">
            <div class="create_access">
              <a href="#" id="video_modal"><i class="icon36 icon36_add"></i>
                <strong>从素材库中选择</strong></a>
            </div>
            <div class="create_access">
              <a href="#"><i class="icon36 icon36_add"></i>
                <strong>新建视频</strong></a>
            </div>
          </div>
        </div>
      </div>
      <div hidden>
        <input id="currentAccountId" value=<%= session[:current_official_account_id] %>/>
        <%= text_field :wx_auto_response, :event_type %>
        <%= text_field :wx_auto_response, :res_type %>
      </div>
      <div class="results" style="position: fixed;left: 35%;top: 0;" hidden>删除成功</div>

    </div>
    <div class="tool_bar">
      <button class="btn btn_primary" type="button" id="saveAutoResponse">保存</button>
      <button class="btn btn_primary cancel" id="delAutoResponse">删除回复</button>
          <div class="mod-popover" hidden>
            <div class="mod-popover_arrow"></div>
            <div class="mod-popover_inner">
              <div class="popover_content">删除后，关注该公众号的用户将不再接收该回复，确定删除？</div>
              <div class="popover_bar">

                <button class="btn btn_primary remove_response">确认</button>
                <button class=" btn btn_primary cancel">取消</button>
              </div>
            </div>
          </div>
    </div>








<% end %>


<%= content_for :js do %>
    <%= javascript_include_tag 'webuploader/webuploader.js', 'data-turbolinks-track' => true %>

    <script type="text/javascript">
      var autoObject = {
        wx_auto_response: {
          res_content: "",
          event_type: 1,
          res_type: 1
        }
      };

      var groupMap = <%= raw @group_map.to_json%>;
      var groupName = <%= raw @group_name_map.to_json%>;

      // page initial event
      $(function () {
        //初始化页面的时候，把被添加自动回复的内容放在页面上
        dataInitial();

        //页面的所有事件绑定
        bindPageEvents();

        $.WebUploader({
          // 选完文件后，是否自动上传。
          auto: true,
          // swf文件路径
          swf: '<%= asset_path 'webuploader/Uploader.swf' %>',
          // 文件接收服务端。
          server: '<%= wx_articles_resources_path %>',
          // 选择文件的按钮。可选。
          // 内部根据当前运行是创建，可能是input元素，也可能是flash.
          pick: '#filePicker1',
          fileVal: 'file',
          fileQueued: function (file) {
          },
          uploadProgress: function (file, percentage) {
            $(".results").html("上传中.....");
            $(".results").show();

          },
          uploadSuccess: function (file,json) {
            autoObject.wx_auto_response.res_content = json.file_id;
            var filename = json.content;
            $(".auto_img_choice").hide();
            $("#img_item img").attr("src",  filename);
            $("#img_item").show();
          },
          uploadError: function (file) {
            $(".results").html("上传失败");
            $(".results").show();
            setTimeout(function () {
              $(".results").hide();
            }, 1000);
          },
          uploadComplete: function (data) {
            $(".results").hide();
          }
        });


      });


      //初始化被添加自动回复的界面初始化
      function dataInitial() {


        var current_account_id = '<%= session[:current_official_account_id] %>';
        //如果session中没有current_official_account_id ，弹出选择框
        if (current_account_id == '') {
//          $("#account_choice").show();
          $("#mask_select_account,#pop_account_select").show();
          return;
        }


        //弹出层的可拖拽设置
        $("#img_choice_popup").draggable();

        //解决webloader隐藏快无法在hide状态下加载的问题
        $(".tabOutList").show();
        setTimeout(function () {
          $(".tabOutList").hide();
        }, 100);

        // 解决webloader的错误
        setTimeout(function () {
          $(".webuploader-element-invisible").hide();

          switch ($("#wx_auto_response_res_type").val()) {
            case '1':
              $("#res_text").trigger("click");
              break;
            case '2':
              $(".auto_img_choice").hide();
              $("#img_item").show();
              <%	if @wx_resource != nil  %>
                var imgname = '<%=	@wx_resource.file_url  %>';
                $("#img_item img").attr("src", imgname);
                <% end %>
              $("#res_pic").trigger("click");
              break;
            case '3':
              $("#res_audio").trigger("click");
              break;
            case '4':
              $("#res_vedio").trigger("click");
              break;
            default:
              $("#res_text").trigger("click");
          }
        }, 100);










      }


      //页面的事件绑定
      function bindPageEvents() {
        // 删除上传的图片
        $("#auto_img_del").on("click", function () {
          autoObject.wx_auto_response.res_content = "";
          $("#img_item").hide();
          $(".auto_img_choice").show();
        });


        //点击回复类型的事件绑定
        $("#tabListA li").on("click", function () {
          $("#wx_auto_response_res_type").val($(this).attr("data-value"));
          autoObject.wx_auto_response.res_type = parseInt($(this).attr("data-value"));
        });


        //给所有的回复类型增加点击样式
        $("#tabListA li").each(function () {
          $(this).click(function () {
            $(this).addClass("hot").siblings("li").removeClass();
            $("#tabOutBoxA .tabOutList:eq(" + $(this).index() + ")").show().siblings("div").hide();
          });
        });


        //保存按钮的点击事件
        $("#saveAutoResponse").on("click", function (event) {

          //check内容的正确性
          if (autoObject.wx_auto_response.res_type == 1) {  //文字
            if ($(".edit_area textarea").val().trim() == "") {
              showMessage("文字必须为1到600个字");
              return;
            }
            autoObject.wx_auto_response.res_content = $(".edit_area > textarea").val();
          } else if (autoObject.wx_auto_response.res_type == 2) {    //图片
            if ($("#img_item").is(":hidden")) {
              showMessage("请添加素材");
              return;
            }
          }


          var actionUrl;
          <% if @wx_auto_response.nil? %>
          actionUrl = '<%=create_response_wx_auto_responses_path %>';
          <% else %>
          actionUrl = '<%=update_response_wx_auto_responses_path %>';

          <% end %>


          $.ajax({
            type: 'POST',
            url: actionUrl,
            dataType: 'json',
            data: autoObject,
            success: function (data) {
              if (data.result == 'success') {
                showMessage("保存成功");
              } else {
                showMessage("保存失败");
              }
            }
          });
        });


        //删除自动回复消息的按钮点击事件
        $("#delAutoResponse").click(function(){
          $(".mod-popover").show();
        });


        // 确认删除此自动回复
        $(".mod-popover .remove_response").click(function(){

          $.ajax({
            type: 'get',
            url: '<%=delete_response_wx_auto_responses_path %>',
            dataType: 'json',
            data: {event_type:1},
            success: function (data) {
              if (data.result == 'success') {
                showMessage("删除成功");
                location.reload();
              } else {
                showMessage("已删除");
                location.reload();
              }
            }
          });


        });

        // 取消删除此自动回复
        $(".mod-popover .cancel").click(function(){
          $(".mod-popover").hide();
        });



        //从素材库添加的点击按钮的事件绑定
        $("#img_modal").click(function(){
          $("#mask,#img_choice_popup").show();

          // 默认选择的是为分组的图片展示出来
          $(".js_group dd[data-groupid=1]").trigger("click");

        });

        // 确定选中的图片
        $("#img_choice_confirm").click(function(){
          $("#mask,#img_choice_popup").hide();

          var media_id = $("label.frm_checkbox_label.selected").parent().attr("resource-id");

          autoObject.wx_auto_response.res_content = media_id;
          $(".auto_img_choice").hide();
          $("#img_item img").attr("src",  $("label.frm_checkbox_label.selected>img").attr("src"));
          $("#img_item").show();
        });


        /* －－－－－－－－－－－－ 事件绑定方法结束　－－－－－－－－－－－－*/
      }


      //提示消息框
      function showMessage(msg) {
        $(".results").html(msg);
        $(".results").show();
        setTimeout(function () {
          $(".results").hide();
        }, 1000);
      }

    </script>
<% end %>
<!--主体结束-->

app/views/wx_auto_responses/new.html.erb
<%= content_for :css do %>
    <%= stylesheet_link_tag 'master', media: 'all', 'data-turbolinks-track' => true %>
<% end %>

<h2>new page.....</h2>
<%= render 'form' %>

<!-- <div class="col_main">
<div class="main"> 
<div class="main_hd">
  <h2>自动回复new</h2>
  <div class="id_wechat">亚信WIFI<a href="javascript:void(0)" class="replace">切换公众号</a></div>
</div>
	
</div>
</div> -->

app/views/wx_auto_responses/show.html.erb
<p id="notice"><%= notice %></p>


<div class="col_main">
<div class="main"> 
<div class="main_hd">
  <h2>自动回复show</h2>
  <div class="id_wechat">亚信WIFI<a href="javascript:void(0)" class="replace">切换公众号</a></div>
</div>
	<%= render 'form' %>
</div>
</div>



<%= link_to 'Edit', edit_wx_auto_response_path(@wx_auto_response) %> |
<%= link_to 'Back', wx_auto_responses_path %>

app/views/wx_auto_responses/subscribe_response.html.erb
<%= content_for :response do %>
        <div id="tabBoxA" class="tabBox">
          <ul class="tabList" id="tabListA">
            <li class="hot" id="res_text"><i class="icon_txt"></i>文字</li>
            <li id="res_pic"><i class="icon_txt icon_img"></i>图片</li>
            <li id="res_audio"><i class="icon_txt icon_voice"></i>语音</li>
            <li id="res_vedio"><i class="icon_txt icon_video"></i>视频</li>
          </ul>
          <div id="tabOutBoxA">   
            <!--文字-->
            <div class="tabOutList">
              <div class="edit_area">
                <%= text_area :wx_auto_response, :res_content %>
              </div>
              <div class="editor_toolbar"><div class="editor_tip">还可以输入591字</div></div> 
            </div>
            <!--图片-->
            <div class="tabOutList" style="display: none;"> 
              <div class="inner">
                <div class="create_access">
                  <a href="#" id="img_modal"><i class="icon36 icon36_add"></i>
                  <strong>从素材库中选择</strong></a>
                </div>
                <div class="create_access">
                  <a href="#"><i class="icon36 icon36_add"></i>
                  <strong>上传图片</strong></a>
                </div>
              </div>
             </div>
            <!--语音-->
            <div class="tabOutList" style="display: none;"> 
            <div class="inner">
                <div class="create_access">
                  <a href="#" id="audio_modal"><i class="icon36 icon36_add"></i>
                  <strong>从素材库中选择</strong></a>
                </div>
                <div class="create_access">
                  <a href="#"><i class="icon36 icon36_add"></i>
                  <strong>新建语音</strong></a>
                </div>
              </div>
             </div>
            <!--视频-->
            <div class="tabOutList" style="display: none;">
            <div class="inner">
                <div class="create_access">
                  <a href="#" id="video_modal"><i class="icon36 icon36_add"></i>
                  <strong>从素材库中选择</strong></a>
                </div>
                <div class="create_access">
                  <a href="#"><i class="icon36 icon36_add"></i>
                  <strong>新建视频</strong></a>
                </div>
              </div>
             </div>
          </div>
        </div>


        <div hidden>
          <input id="currentAccountId" value= <%= session[:current_official_account_id] %> />
          <%= text_field :wx_auto_response, :event_type %>
          <%= text_field :wx_auto_response, :res_type %>
        </div> 
        <div class="results" style="left: 20%;" hidden>删除成功</div>

<% end %>