config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  scope 'wxoss' do
    mount WeixinRailsMiddleware::Engine, at: "/"

    constraint = lambda { |request| !request.session[:admin].blank? }
    constraints constraint do
      mount Sidekiq::Web, at: '/sidekiq', as: :sidekiq
    end

    get "wx_official_accounts/getAccountList", to: 'wx_official_accounts#getAccountList'
    get "wx_official_accounts/setOfficialAccount2Session", to: 'wx_official_accounts#setOfficialAccount2Session'
    resources :wx_official_accounts do
      get 'get_resources', on: :member
      get 'get_users', on: :member
      resources :wx_auto_response

    end

    get 'welcome/index'
    post 'welcome/login'
    get 'welcome/getmenu'
    get 'welcome/logout'
    get 'wx_articles/resources'  => 'wx_resources#index'
    post 'wx_articles/resources'  => 'wx_resources#create'
    get 'wx_articles/resources/getimgdata' => 'wx_resources#getimgdata'
    post 'wx_articles/resources/create_group' => 'wx_resources#create_group'
    post 'wx_articles/resources/modify_img_group' => 'wx_resources#modify_img_group'
    post 'wx_articles/resources/modify_group' => 'wx_resources#modify_group'
    post 'wx_articles/resources/del_group' => 'wx_resources#del_group'
    post 'wx_articles/resources/rename' => 'wx_resources#rename'
    post 'wx_articles/resources/delete_image' => 'wx_resources#destroy'
    get 'wx_articles/edit' => 'wx_articles#edit'
    post 'wx_articles/delete' => 'wx_articles#destroy'
    resources :wx_articles

    post 'wx_users/get_fans_info'
    post 'wx_users/add_mark'
    post 'wx_users/create_group'
    post 'wx_users/rename_group'
    post 'wx_users/del_group'
    get 'wx_users/get_user_list'
    post 'wx_users/search'
    post 'wx_users/batch_set_tag'
    post 'wx_users/del_tag'
    post 'wx_users/set_black'
    post 'wx_users/cancle_black'
    post 'wx_users/fixgroupcnt'
    resources :wx_users
    get 'wx_msganalysis' => 'wx_msganalysis#index'
    get 'wx_msganalysis/keyword' => 'wx_msganalysis#keyword'
    get 'wx_msganalysis/fdevreport' => 'wx_msganalysis#fdevreport'
    get 'wx_interfaceanalysis' => 'wx_interfaceanalysis#index'
    get 'wx_useranalysis' => 'wx_useranalysis#index'

    get 'wxserver/netauth' => 'wxserver#netauth'

    resources :wx_batch_messages do
      get 'get_provinces_by_country_id', on: :collection
      get 'get_cities_by_province_id', on: :collection
      post 'batchSendMessage', on: :collection
      get 'batch_messages_history', on: :collection
      get 'delete_message', on: :collection
    end

    resources :wx_auto_responses do
      post 'update_response', on: :collection
      post 'create_response', on: :collection
      get 'delete_response', on: :collection
      post "create_key_response", on: :collection
      get "delete_wx_key_response", on: :collection
      post 'update_key_response', on: :collection
    end

    resources :wx_menus do
      post 'create_menu', on: :collection
    end

    resources :wx_shake_activities do
      get 'redirect', on: :collection
      get 'screenshow', on: :collection
      get 'runway', on: :collection
      get 'get_userdata', on: :collection
      get 'awardlist', on: :collection
      get 'update_status', on: :collection
      get 'get_status', on: :collection
      post 'save_count', on: :collection
      get 'get_awardstatus', on: :collection
    end

    resources :wx_shake_managements do
      get 'prizelist', on: :collection
      post 'uploadpic', on: :collection
      post 'deletepic', on: :collection
    end

    resources :wx_wheel_activities do
      get 'redirect', on: :collection
      get 'wheel', on: :collection
      post 'update_info', on: :collection
      get 'query_record', on: :collection
    end

    resources :wx_wheel_managements do
      get 'prizelist', on: :collection
    end

  end

  root 'welcome#index'

end

app/controllers/wx_wheel_managements_controller.rb
class WxWheelManagementsController < WeixinClientController
  layout 'application'
  before_action :set_wx_activity, only: [:show, :edit, :update, :destroy]

  def index
    unless @current_wx_official_account.nil?
      @wx_activities = WxActivity.where(activity_type: 2, wx_official_account_id: @current_wx_official_account.id)
      @wx_activities.each do |wx_activity|
        # -1代表活动未开始，1代表活动进行中，99代表活动已结束
        nowtime = Time.now.strftime("%Y-%m-%d %H:%M:%S")
        begintime = wx_activity.begintime.strftime("%Y-%m-%d %H:%M:%S")
        endtime = wx_activity.endtime.strftime("%Y-%m-%d %H:%M:%S")
        if nowtime < begintime
          wx_activity.update(status: -1)
        end
        if nowtime >= begintime && nowtime <= endtime
          wx_activity.update(status: 1)
        end
        if nowtime > endtime
          wx_activity.update(status: 99)
        end
      end
    end
  end

  def show
  end

  def new
    @wx_activity = WxActivity.new
  end

  def edit
  end

  def create
    wx_activity = WxActivity.new(wheel_activity_params)
    wx_activity.activity_type = 2  #2代表大转盘
    wx_activity.wx_official_account_id = @current_wx_official_account.id
    activity_flag = false
    activity_award_flag = false
    if wx_activity.save
      activity_flag = true
    end
    params[:award_list].each_pair do |key, val|
      level = val['level']
      name = val['name']
      amount = val['amount']
      probability = val['probability']
      imgurl = val['imgurl']
      wx_activity_award = WxActivityAward.new(wx_activity_id: wx_activity.id, level: level, name: name, imgurl: imgurl, amount: amount, probability: probability)
      if wx_activity_award.save
        activity_award_flag = true
      end
    end
    if activity_flag && activity_award_flag
      render json: {"result" => "success"}
    else
      render json: {"result" => "false"}
    end
  end

  def update
    activity_flag = false
    activity_award_flag = false
    if @wx_activity.update(wheel_activity_params)
      activity_flag = true
    end
    if @wx_activity_awards.length == params[:award_list].length
      @wx_activity_awards.each do |wx_activity_award|
        params[:award_list].each_pair do |key, val|
          if wx_activity_award.level == val['level'].to_i
            name = val['name']
            amount = val['amount']
            probability = val['probability']
            imgurl = val['imgurl']
            if wx_activity_award.update(name: name, imgurl: imgurl, amount: amount, probability: probability)
              activity_award_flag = true
            end
          end
        end
      end
    else
      @wx_activity_awards.each do |wx_activity_award|
        wx_activity_award.destroy
      end
      params[:award_list].each_pair do |key, val|
        level = val['level']
        name = val['name']
        amount = val['amount']
        probability = val['probability']
        imgurl = val['imgurl']
        wx_activity_award = WxActivityAward.new(wx_activity_id: @wx_activity.id, level: level, name: name, imgurl: imgurl, amount: amount, probability: probability)
        if wx_activity_award.save
          activity_award_flag = true
        end
      end
    end
    if activity_flag && activity_award_flag
      render json: {"result" => "success"}
    else
      render json: {"result" => "false"}
    end
  end

  def destroy
    @wx_activity.destroy
    @wx_activity_awards.destroy_all
    wx_activity_users = WxActivityUser.where(wx_activity_id: params[:id])
    wx_activity_users.destroy_all
    respond_to do |format|
      format.html { render :text => '' }
      format.json { head :no_content }
    end
  end

  def prizelist
    @prize_list = Array.new
    wx_activity_users = WxActivityUser.where('wx_activity_id = '+params[:format]+' and award_level is not null').order("award_level ASC")
    wx_activity_users.each do |user|
      temp = Hash.new
      wx_activity_award = WxActivityAward.where(wx_activity_id: params[:format], level: user.award_level).select('name')
      temp['award_name'] = wx_activity_award[0].name
      wx_user = WxUser.where(openid: user.openid).select('nickname')
      temp['nickname'] = wx_user[0].nickname
      temp['realname'] = user.realname
      temp['telephone'] = user.telephone
      temp['address'] = user.address
      @prize_list.push(temp)
    end
    render 'wx_wheel_managements/prizelist'
  end

  private
  def set_wx_activity
    @wx_activity = WxActivity.find(params[:id])
    @wx_activity_awards = WxActivityAward.where(wx_activity_id: @wx_activity.id)
  end

  def wheel_activity_params
    wx_wheel_params = Hash.new
    wx_wheel_params[:name] = params[:name]
    wx_wheel_params[:begintime] = params[:begintime]
    wx_wheel_params[:endtime] = params[:endtime]
    wx_wheel_params[:description] = params[:description]
    wx_wheel_params[:lottery_num] = params[:lottery_num]
    if(params[:is_repeat_draw] == "true")
      wx_wheel_params[:is_repeat_draw] = 1
    else
      wx_wheel_params[:is_repeat_draw] = 0
    end
    if(params[:receive_way] == "0")
      wx_wheel_params[:receive_way] = 0
    else
      wx_wheel_params[:receive_way] = 1
      wx_wheel_params[:offline_address] = params[:offline_address]
      wx_wheel_params[:offline_description] = params[:offline_description]
    end
    unless params[:receive_info].nil?
      wx_wheel_params[:receive_info] = params[:receive_info]*","
    end
    return wx_wheel_params
  end

end

app/helpers/wx_wheel_managements_helper.rb
module WxWheelManagementsHelper
end

app/views/wx_wheel_managements/edit.html.erb
<%= content_for :css do %>
    <%= stylesheet_link_tag 'widget/jquery.datetimepicker.css', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'wx_shake_managements', 'data-turbolinks-track' => true %>
<% end %>
<%= content_for :content do %>
    <div class="col_main setup">
      <div class="main_hd">
        <h2>大转盘管理</h2>
        <div class="page_nav">
          <%= link_to '返回上一层', wx_wheel_managements_path, :class => 'icon_goback' %>
          <%= link_to '大转盘管理', wx_wheel_managements_path %>&nbsp;/&nbsp;编辑大转盘
        </div>
      </div>
      <div class="main_bd">
        <form>
            <div class="shake_meta">
              <div class="frm_control_group">
                <label for class="frm_label">活动名称</label>
                <div class="frm_controls">
                <span class="frm_input_box counter_in append ">
                  <input type="text" class="frm_input frm_msg_content" id="name" maxlength="35" value="<%= @wx_activity.name %>"/>
                </span>
                  <p class="frm_msg fail" style="display: none;">请输入活动名称</p>
                  <p class="frm_tips">活动名称只用于管理，不显示在下发的活动内容中</p>
                </div>
              </div>
            </div>
            <div class="shake_meta time_setting">
              <div class="frm_control_group">
                <label for class="frm_label">开始时间</label>
                <div class="frm_controls">
                  <div class="date_select timepicker">
                    <div class="datepicker_area">
                    <span class="btn datepicker_switch">
                      <input type="text" class="frm_input" id="datetimepicker_begin" value="<%= @wx_activity.begintime.strftime("%Y-%m-%d %H:%M") %>"/>
                      <i class="icon_datepicker"></i>
                    </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="shake_meta time_setting">
              <div class="frm_control_group">
                <label for class="frm_label">结束时间</label>
                <div class="frm_controls">
                  <div class="date_select timepicker">
                    <div class="datepicker_area">
                    <span class="btn datepicker_switch">
                      <input type="text" class="frm_input" id="datetimepicker_end" value="<%= @wx_activity.endtime.strftime("%Y-%m-%d %H:%M") %>"/>
                      <i class="icon_datepicker"></i>
                    </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="shake_meta">
              <div class="frm_control_group">
                <label for class="frm_label">抽奖限制</label>
                <div class="frm_controls">
                  <span>每人抽奖机会</span><span class="frm_input_box frm_small m_lr">
                  <input type="text" class="frm_input frm_msg_content" id="lottery_num" value="<%= @wx_activity.lottery_num %>"/></span><span>次</span>
                  <p><label class="radio-label"><input type="checkbox" name="" id="is_repeat_draw" >支持每天可重复抽奖</label></p>
                </div>
              </div>
            </div>
            <div class="shake_meta">
              <div class="frm_control_group">
                <label for class="frm_label">活动说明</label>
                <div class="frm_controls">
                  <div class="emotion_editor">
                    <textarea style="height:150px; width:740px;" maxlength="300"><%= @wx_activity.description %></textarea>
                    <div class="editor_toolbar"><div class="editor_tip">最多可以输入300字,按下Shift+Enter键换行</div></div>
                  </div>
                </div>
              </div>
            </div>
          <div class="shake_meta">
            <div class="frm_control_group">
              <label for class="frm_label">领奖方式</label>
              <div class="frm_controls">
                <label class="radio-label" id="j_mail">
                  <input type="radio" name="RadioGroup1" value="单选" id="RadioGroup1_0" />
                  邮寄/直接发放</label>
                <p class="frm_tips m_l20">用户中奖后通过表单来登记领奖信息。</p>
                <div id="j_mail_info" class="hide"><p class="frm_info m_l20"><label class="radio-label"><input type="checkbox" name="realname" id="" >姓名</label><label class="radio-label"><input type="checkbox" name="telephone" id="" >手机</label><label class="radio-label"><input type="checkbox" name="address" id="" >地址</label></p></div>
                <br />
                <label class="radio-label" id="j_offline">
                  <input type="radio" name="RadioGroup1" value="单选" id="RadioGroup1_1" />
                  线下兑奖</label>
                <div class="m_l20">
                  <p class="frm_tips">用户到线下兑奖，由商家进行核销。</p>
                  <div id="j_offline_info" class="hide"><br />
                    <p>是否需要中奖者填写信息<span class="frm_tips">(请勿要求填写与领奖无关的隐私信息）</span><br/><label class="radio-label" id="j_win" ><input type="checkbox" id="j_win_btn" >需要</label></p>
                    <p class="frm_info hide" id="j_win_info"><label class="radio-label"><input type="checkbox" name="realname" id="" >姓名</label><label class="radio-label"><input type="checkbox" name="telephone" id="" >手机</label></p><br />
                    <p>线下领奖地址<br/><span class="frm_input_box counter_in append ">
                        <input type="text" class="frm_input frm_msg_content" style="color:#8d8d8d"  onFocus="if(this.value=='请填写领奖地址'){this.value='';this.style.color='#8d8d8d'};" onblur="if(this.value==''){this.value='请填写领奖地址';this.style.color='#8d8d8d'}"  value="请填写领奖地址" />
                      </span></p><br/>
                    <p>线下领奖时间说明<br/><span class="frm_input_box counter_in append ">
                        <input type="text" class="frm_input frm_msg_content" style="color:#8d8d8d"  onFocus="if(this.value=='如：每天下午3:00~5:00'){this.value='';this.style.color='#8d8d8d'};" onblur="if(this.value==''){this.value='如：每天下午3:00~5:00';this.style.color='#8d8d8d'}"  value="如：每天下午3:00~5:00" />
                      </span></p></div>
                </div>
              </div>
            </div>
          </div>
        </form>
        <div class="shake_meta">
          <span>奖项设置<span class="frm_tips">（上传图片的最佳尺寸：300像素*300像素，其他尺寸会影响页面效果，格式png，jpeg，jpg，gif。大小不超过1M）</span></span>
          <div class="shake_meta_container">
            <div class="shake_container_dec shake_add">
              <a class="btn btn_default btn_add btn_shake_add" href="javascript:;">添加奖项</a>
            </div>
            <div class="shake_container_dec shake_del">
              <a class="btn btn_default btn_del btn_shake_del" href="javascript:;">删除奖项</a>
            </div>
          </div>
        </div>
      </div>
      <div class="tool_bar tc" style="margin-top:60px;"><button class="btn btn_primary">完成</button></div>
    </div>
    <div class="results hide" style="position: fixed;left: 35%;top: 0;">删除成功</div>
<% end %>
<%= content_for :js do %>
    <%= javascript_include_tag 'activity/jquery.datetimepicker.full', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'webuploader/webuploader.js', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'wx_wheel_managements', 'data-turbolinks-track' => true %>

    <script type="text/javascript">
      $(function(){
        var wx_activity_awards = <%= raw @wx_activity_awards.to_json%>;
        $(wx_activity_awards).each(function(index) {
          var level = wx_activity_awards[index].level;
          var name = wx_activity_awards[index].name;
          var amount = wx_activity_awards[index].amount;
          var probability = wx_activity_awards[index].probability;
          var imgurl = wx_activity_awards[index].imgurl;
          var shake_num = null;
          switch(level)
          {
            case 1:
              shake_num = "一等奖";
              break;
            case 2:
              shake_num = "二等奖";
              break;
            case 3:
              shake_num = "三等奖";
              break;
            case 4:
              shake_num = "四等奖";
              break;
            case 5:
              shake_num = "五等奖";
              break;
          }
          var option_setting = $('<div class="shake_meta option_setting">' +
              '<form class="">' +
              '<div class="shake_meta_title group"><span class="shake_num">一等奖</span></div>' +
              '<div class="shake_meta shake_meta_content">' +
              '<div class="award">' +
              '<div class="shake_meta_detail"><div class="frm_control_group"><label for class="frm_label">奖品名称</label>' +
              '<div class="frm_controls"><span class="frm_input_box counter_in append "><input type="text" class="frm_input frm_msg_content" maxlength="35" /></span></div></div></div>' +
              '<div class="shake_meta_detail"><div class="frm_control_group"><label for class="frm_label" >数&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;量</label>' +
              '<div class="frm_controls"><span class="frm_input_box frm_small"><input type="text" class="frm_input frm_msg_content" /></span><span class="number_of">个</span></div></div>' +
              '<div class="frm_control_group"><label for class="frm_label" >概&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;率</label><div class="frm_controls"><span class="frm_input_box frm_small">' +
              '<input type="text" class="frm_input frm_msg_content" /></span><span class="number_of">%</span><span class="frm_tips">可设置范围（0.01%~100%）</span>' +
              '<p class="frm_tips">每次转动转盘后获得该奖品的概率，与该奖品数量无关</p></div></div></div>' +
              '<div class="prize_bar"><div id="filePicker">上传图片</div><div class="prize_img hide"><img src="" alt=""/><a href="javascript:;">删除</a></div></div></div>' +
              '</div></form></div>');
          option_setting.find('.shake_num').text(shake_num);
          option_setting.find('.frm_msg_content').eq(0).val(name);
          option_setting.find('.frm_msg_content').eq(1).val(amount);
          option_setting.find('.frm_msg_content').eq(2).val(probability);
          if (imgurl != "" && imgurl != null){
            option_setting.find('.prize_img img').attr('src',imgurl);
            option_setting.find('.prize_bar #filePicker').hide();
            option_setting.find('.prize_img').show();
          }
          option_setting.insertBefore($('.shake_container_dec.shake_add'));
        });

        picHandle();  // 上传图片事件初始化

        var wx_activity = <%= raw @wx_activity.to_json%>;
        if(wx_activity.is_repeat_draw){
          $('#is_repeat_draw').prop('checked','true');
        }
        if(wx_activity.receive_way == 0){
          $('#RadioGroup1_0').prop('checked','true');
          $("#j_mail_info").show();
          if(wx_activity.receive_info.indexOf('realname')!=-1){
            $("#j_mail_info input[name='realname']").prop('checked','true');
          }
          if(wx_activity.receive_info.indexOf('telephone')!=-1){
            $("#j_mail_info input[name='telephone']").prop('checked','true');
          }
          if(wx_activity.receive_info.indexOf('address')!=-1){
            $("#j_mail_info input[name='address']").prop('checked','true');
          }
        }else {
          $('#RadioGroup1_1').prop('checked','true');
          $("#j_offline_info").show();
          if(wx_activity.receive_info != null){
            $('#j_win_info').show();
            $('#j_win_btn').prop('checked','true');
            if(wx_activity.receive_info.indexOf('realname')!=-1){
              $("#j_win_info input[name='realname']").prop('checked','true');
            }
            if(wx_activity.receive_info.indexOf('telephone')!=-1){
              $("#j_win_info input[name='telephone']").prop('checked','true');
            }
            if(wx_activity.receive_info.indexOf('address')!=-1){
              $("#j_win_info input[name='address']").prop('checked','true');
            }
          }
          if(wx_activity.offline_address != null){
            $("#j_offline_info input[type='text']").eq(0).val(wx_activity.offline_address);
          }
          if(wx_activity.offline_description != null){
            $("#j_offline_info input[type='text']").eq(1).val(wx_activity.offline_description);
          }
        }

        $('.tc .btn_primary').click(function(){
          $.ajax({
            type: 'PATCH',
            url: '/wxoss/wx_wheel_managements/'+wx_activity.id,
            dataType: 'json',
            data: getWheelInfo(),
            success: function (data) {
              if (data.result == 'success') {
                msgShow("更新成功");
                document.location.href = '/wxoss/wx_wheel_managements/'+wx_activity.id;
              } else {
                msgShow("更新失败");
              }
            }
          });
        });
      });
    </script>

<% end %>

app/views/wx_wheel_managements/index.html.erb
<%= content_for :content do %>
    <div class="main_hd">
      <h2>大转盘管理</h2>
    </div>
    <div class="main_bd">
      <div class="topbar top_bor">
        <%= button_to '新建大转盘', new_wx_wheel_management_path, class: "btn btn_add btn_new", method: :get %>
      </div>

      <div class="table_wrp with_border">
        <table class="J_table_hover data-table">
          <thead>
          <tr>
            <th>大转盘名称</th>
            <th>开始时间</th>
            <th>结束时间</th>
            <th>状态</th>
            <th>操作</th>
          </tr>
          </thead>
          <tbody>
          <% if @wx_activities.nil? || @wx_activities.empty? %>
              <tr>
                <td colspan="5">
                  <div class="empty_tips">
                    <p>你还没有创建任何大转盘活动</p>
                  </div>
                </td>
              </tr>
          <% else %>
              <% @wx_activities.each do |wx_activity| %>
                  <tr>
                    <td class="name"><%= wx_activity.name %></td>
                    <td><%= wx_activity.begintime.strftime('%Y-%m-%d %H:%M') %></td>
                    <td><%= wx_activity.endtime.strftime('%Y-%m-%d %H:%M') %></td>
                    <% case wx_activity.status %>
                    <% when -1 %>
                        <td class="col2">未开始</td>
                        <td>
                          <%= link_to '编辑', edit_wx_wheel_management_path(wx_activity) %>
                          <%= link_to '详情', wx_wheel_management_path(wx_activity) %>
                          <%= link_to '参与地址', '', :class => 'link', :wx_activity_id =>wx_activity.id %>
                          <%= link_to '删除', wx_wheel_management_path(wx_activity), method: :delete, :class => 'remove' %>
                        </td>
                    <% when 1 %>
                        <td class="col2">进行中</td>
                        <td>
                          <%= link_to '获奖名单', prizelist_wx_wheel_managements_path(wx_activity) %>
                          <%= link_to '详情', wx_wheel_management_path(wx_activity) %>
                          <%= link_to '参与地址', '', :class => 'link', :wx_activity_id =>wx_activity.id %>
                          <%= link_to '删除', wx_wheel_management_path(wx_activity), method: :delete, :class => 'remove' %>
                        </td>
                    <% when 99 %>
                        <td>已结束</td>
                        <td>
                          <%= link_to '获奖名单', prizelist_wx_wheel_managements_path(wx_activity) %>
                          <%= link_to '详情', wx_wheel_management_path(wx_activity) %>
                          <%= link_to '参与地址', '', :class => 'link', :wx_activity_id =>wx_activity.id %>
                          <%= link_to '删除', wx_wheel_management_path(wx_activity), method: :delete, :class => 'remove' %>
                        </td>
                    <% end %>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
<% end %>
<%= content_for :js do %>
    <%= javascript_include_tag 'ZeroClipboard/ZeroClipboard.js', 'data-turbolinks-track' => true %>
    <script>
      $(function () {
        //页面初始化
        var current_account_id = '<%= session[:current_official_account_id] %>';
        //如果session中没有current_official_account_id ，弹出选择框
        if (current_account_id == '') {
          $("#mask_select_account,#pop_account_select").show();
          return;
        }

        $('a.remove').click(function () {
          var activity_name = $(this).parent().parent().find(".name").html();
          $(".mod-popover").remove();
          $(this).after('<div class="mod-popover" style="left:70px"><div class="mod-popover_arrow"></div>' +
              '<div class="mod-popover_inner" style="width: 234px;"><div class="popover_content">确定要删除 '+activity_name+' 活动吗？</div>' +
              '<div class="popover_bar"><button class="btn btn_primary remove">确认</button><button ' +
              'class="btn btn_primary cancel">取消</button></div></div></div>');
          var deleteLink = $(this);
          $("button.remove").on('click', function () {
            $.ajax({
              type: "DELETE",
              url: deleteLink.attr("href"),
              success: function (data) {
                $('<div class="results"  style="position:fixed;z-index:999;top:0px ">删除成功</div>').appendTo("body");
                location.reload();
              },
              error: function (msg) {
                $('<div class="results"  style="position:fixed;z-index:999;top:0px ">删除失败</div>').appendTo("body");
                location.reload();
              }
            });
          });
          $("button.cancel").on('click', function () {
            $(".mod-popover").remove();
          });
          return false;
        });

        $('a.link').click(function () {
          $(".mod-popover").remove();
          //获取主机地址，如： http://localhost:8083
          var curWwwPath = window.document.location.href;
          var pathName = window.document.location.pathname;
          var pos = curWwwPath.indexOf(pathName);
          var localhostPath = curWwwPath.substring(0, pos);
          $(this).after('<div class="mod-popover" style="left:15px"><div class="mod-popover_arrow"></div>' +
              '<div class="mod-popover_inner" style="width: 234px;"><input type="text" id="address" value="'+localhostPath+'/wxoss/wx_wheel_activities?wx_activity_id='+$(this).attr('wx_activity_id')+'">' +
              '<div class="popover_bar"><button class="btn btn_primary copy" data-clipboard-target="address">复制</button><button ' +
              'class="btn btn_primary cancel">取消</button></div></div></div>');
          var client = new ZeroClipboard($('.copy'));
          client.on( "ready", function( readyEvent ) {
            // alert( "ZeroClipboard SWF is ready!" );

            client.on( "aftercopy", function( event ) {
              // `this` === `client`
              // `event.target` === the element that was clicked
              //alert("Copied text to clipboard: " + event.data["text/plain"] );
              $('<div class="results"  style="position:fixed;z-index:999;top:0px ">已复制到剪贴板</div>').appendTo("body");
              setTimeout(function () {
                $(".results").hide();
              }, 1000);
            });
          });
          $("button.cancel").on('click', function () {
            $(".mod-popover").remove();
          });
          return false;
        });

      });
    </script>
<% end %>

app/views/wx_wheel_managements/prizelist.html.erb
<%= content_for :content do %>
    <div class="col_main setup">
      <div class="main_hd">
        <h2>大转盘管理</h2>
        <div class="page_nav">
          <%= link_to '返回上一层', wx_wheel_managements_path, :class => 'icon_goback' %>
          <%= link_to '大转盘管理', wx_wheel_managements_path %>&nbsp;/&nbsp;中奖名单
        </div>
      </div>
      <div class="main_bd">
        <div class="prize_list">
          <div class="table_wrp with_border">
            <table class="J_table_hover data-table">
              <thead>
              <tr>
                <th>奖品名称</th>
                <th>微信名称</th>
                <th>姓名</th>
                <th>手机</th>
                <th>地址</th>
              </tr>
              </thead>
              <tbody>
              <% if @prize_list.nil? || @prize_list.empty? %>
                  <tr>
                    <td colspan="5">
                      <div class="empty_tips">
                        <p>还没有任何中奖信息</p>
                      </div>
                    </td>
                  </tr>
              <% else %>
                  <% @prize_list.each do |prize| %>
                      <tr>
                        <td class="col2"><%= prize['award_name'] %></td>
                        <td class="col2"><%= prize['nickname'] %></td>
                        <td class="col2"><%= prize['realname'] %></td>
                        <td class="col2"><%= prize['telephone'] %></td>
                        <td class="col2"><%= prize['address'] %></td>
                      </tr>
                  <% end %>
              <% end %>
              </tbody>
              </table>
            </div>
        </div>
      </div>
    </div>
<% end %>